name: Testes Unitarios

on:
  push:
    branches:
      - master

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar dependencias
        run: |
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Executar testes
        run: pytest